services:
    Traceway\OpenTelemetryBundle\Tracing:
        autoconfigure: true

    Traceway\OpenTelemetryBundle\TracingInterface:
        alias: Traceway\OpenTelemetryBundle\Tracing

    Traceway\OpenTelemetryBundle\EventSubscriber\OpenTelemetrySubscriber:
        autoconfigure: true

    Traceway\OpenTelemetryBundle\EventSubscriber\ConsoleSubscriber:
        autoconfigure: true

    Traceway\OpenTelemetryBundle\Messenger\OpenTelemetryMiddleware:
        autoconfigure: true

    Traceway\OpenTelemetryBundle\Metrics\MeterRegistry:
        autoconfigure: true

    Traceway\OpenTelemetryBundle\Metrics\MeterRegistryInterface:
        alias: Traceway\OpenTelemetryBundle\Metrics\MeterRegistry

    Traceway\OpenTelemetryBundle\Messenger\OpenTelemetryMetricsMiddleware:
        autoconfigure: true
